/**
 * Columns shared by every entity in the domain model.
 * Correspond to the timestamps and identifier generated by the backend.
 */
export interface BaseEntity {
  id: number;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
}

/**
 * Common shape for catalog-type entities in the domain.
 * Has a unique business `key` identifier, a visible `name`, and an optional `description`.
 */
export interface CatalogEntity<K extends string = string> extends BaseEntity {
  name: string;
  key: K;
  description: string | null;
}
