import {
  Accessibility,
  ArrowLeft,
  ArrowRight,
  Ban,
  Bookmark,
  Calendar,
  Car,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  Clock,
  Coffee,
  ExternalLink,
  Eye,
  EyeOff,
  Heart,
  House,
  Image,
  Inbox,
  Info,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Martini,
  Menu,
  Moon,
  Palette,
  Pencil,
  Plus,
  Route,
  Search,
  Settings,
  Share2,
  Shield,
  SlidersHorizontal,
  Sparkles,
  Star,
  Trash2,
  Trees,
  TriangleAlert,
  User,
  Users,
  Utensils,
  Wallet,
  Wine,
  X,
  type LucideIcon,
} from "lucide-react";

/**
 * Iconografía del proyecto: nombres de Lucide en kebab-case (los mismos que usa
 * el prototipo) mapeados a su componente.
 *
 * Es un registro explícito a propósito. `lucide-react/dynamic` resuelve el icono
 * en el cliente dentro de un `useEffect`, así que ningún icono llega en el HTML
 * del servidor y el bundler tiene que emitir un chunk por cada uno de los ~1600
 * iconos de la librería. Con este mapa los iconos se renderizan en el servidor y
 * solo entran al bundle los que están acá.
 *
 * **Para usar un icono nuevo hay que agregarlo a este mapa.** Importalo de
 * `lucide-react` en PascalCase y sumá la entrada en kebab-case, respetando el
 * orden alfabético. El nombre correcto está en https://lucide.dev/icons.
 */
export const iconRegistry = {
  accessibility: Accessibility,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  ban: Ban,
  bookmark: Bookmark,
  calendar: Calendar,
  car: Car,
  "chart-column": ChartColumn,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  clock: Clock,
  coffee: Coffee,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  heart: Heart,
  house: House,
  image: Image,
  inbox: Inbox,
  info: Info,
  "loader-circle": LoaderCircle,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  martini: Martini,
  menu: Menu,
  moon: Moon,
  palette: Palette,
  pencil: Pencil,
  plus: Plus,
  route: Route,
  search: Search,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  "trash-2": Trash2,
  trees: Trees,
  "triangle-alert": TriangleAlert,
  user: User,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  wine: Wine,
  x: X,
} satisfies Record<string, LucideIcon>;

/** Nombres de icono disponibles. Se deriva del registro: no hay que mantenerlo aparte. */
export type IconName = keyof typeof iconRegistry;
