import {
  Accessibility,
  ArrowLeft,
  ArrowRight,
  Ban,
  Bookmark,
  Calendar,
  Car,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  Clock,
  Coffee,
  ExternalLink,
  Eye,
  EyeOff,
  FolderPlus,
  Heart,
  House,
  Image,
  Inbox,
  Info,
  LayoutDashboard,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  Map,
  MapPin,
  Martini,
  Menu,
  MessageCircle,
  Moon,
  Palette,
  Pencil,
  Plus,
  Repeat,
  Route,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  Tag,
  Target,
  Trash2,
  Trees,
  TrendingUp,
  TriangleAlert,
  Trophy,
  User,
  Users,
  Utensils,
  Wallet,
  Wine,
  X,
  type LucideIcon,
} from "lucide-react";

/**
 * Project iconography: Lucide names in kebab-case (the same ones the
 * prototype uses) mapped to their component.
 *
 * This is deliberately an explicit registry. `lucide-react/dynamic` resolves
 * the icon on the client inside a `useEffect`, so no icon ever reaches the
 * server-rendered HTML, and the bundler would have to emit a chunk for each
 * of the library's ~1600 icons. With this map, icons render on the server
 * and only the ones listed here end up in the bundle.
 *
 * **To use a new icon, add it to this map.** Import it from `lucide-react`
 * in PascalCase and add the kebab-case entry, keeping alphabetical order.
 * The correct name is at https://lucide.dev/icons.
 */
export const iconRegistry = {
  accessibility: Accessibility,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  ban: Ban,
  bookmark: Bookmark,
  calendar: Calendar,
  car: Car,
  "chart-column": ChartColumn,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "circle-alert": CircleAlert,
  "circle-check": CircleCheck,
  clock: Clock,
  coffee: Coffee,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  "folder-plus": FolderPlus,
  heart: Heart,
  house: House,
  image: Image,
  inbox: Inbox,
  info: Info,
  "layout-dashboard": LayoutDashboard,
  "loader-circle": LoaderCircle,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  mail: Mail,
  map: Map,
  "map-pin": MapPin,
  martini: Martini,
  menu: Menu,
  "message-circle": MessageCircle,
  moon: Moon,
  palette: Palette,
  pencil: Pencil,
  plus: Plus,
  repeat: Repeat,
  route: Route,
  search: Search,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  "shield-check": ShieldCheck,
  "sliders-horizontal": SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  tag: Tag,
  target: Target,
  "trash-2": Trash2,
  trees: Trees,
  "trending-up": TrendingUp,
  "triangle-alert": TriangleAlert,
  trophy: Trophy,
  user: User,
  users: Users,
  utensils: Utensils,
  wallet: Wallet,
  wine: Wine,
  x: X,
} satisfies Record<string, LucideIcon>;

/** Available icon names. Derived from the registry: no need to maintain it separately. */
export type IconName = keyof typeof iconRegistry;
